# Dashboard Responsive Testing Guide
# Test dashboard di berbagai ukuran layar

echo "=== Smart Door Lock - Dashboard Responsive Test ==="
echo ""
echo "✅ CHECKLIST:"
echo ""
echo "1. Desktop View (> 800px)"
echo "   - Sidebar di kiri (vertical)"
echo "   - 2-column grid untuk cards"
echo "   - Semua info terlihat (connection status, mini status)"
echo ""
echo "2. Tablet View (800px)"
echo "   - Sidebar jadi horizontal bar di atas"
echo "   - Navigation jadi row (scroll horizontal)"
echo "   - Grid jadi 1-column"
echo "   - Connection status tersembunyi (space saving)"
echo ""
echo "3. Mobile View (< 800px)"
echo "   - Layout full 1-column"
echo "   - Touch targets min 44px"
echo "   - Buttons easy to tap"
echo "   - Chart readable"
echo ""
echo "4. Small Phone (< 480px)"
echo "   - Hero text size reduced (42px)"
echo "   - Compact cards"
echo "   - Vertical button stacking"
echo "   - Chart labels smaller"
echo ""
echo "5. Landscape Mode"
echo "   - Compact padding"
echo "   - Smaller hero text (38px)"
echo "   - Navigation buttons compact"
echo ""
echo "=== TESTING METHODS ==="
echo ""
echo "Method 1: Browser DevTools"
echo "  1. Buka http://localhost:3000"
echo "  2. F12 → Toggle Device Toolbar"
echo "  3. Test breakpoints: 1200px, 800px, 480px, 375px"
echo "  4. Test orientations: portrait, landscape"
echo ""
echo "Method 2: Real Devices"
echo "  1. Get local IP: ipconfig (Windows) / ifconfig (Mac/Linux)"
echo "  2. Buka http://[YOUR_IP]:3000 di HP"
echo "  3. Test di iPhone, Android, tablet"
echo ""
echo "Method 3: Responsive Design Mode (Firefox)"
echo "  1. Ctrl+Shift+M"
echo "  2. Select device presets"
echo "  3. Test touch simulation"
echo ""
echo "✅ PASS Criteria:"
echo "  - Semua text readable (not cut off)"
echo "  - Buttons min 44x44px (easy to tap)"
echo "  - No horizontal scroll (except sidebar nav)"
echo "  - Chart shows properly"
echo "  - Navigation accessible"
echo ""
echo "❌ FAIL Indicators:"
echo "  - Text overflow or cut off"
echo "  - Buttons too small to tap"
echo "  - Layout broken/overlapping"
echo "  - Charts unreadable"
