# Firmware Testing Script
# Untuk memastikan motion detection smooth tanpa lag

echo "=== Smart Door Lock - Firmware Test ==="
echo ""
echo "✅ CHECKLIST:"
echo ""
echo "1. Upload firmware ke ESP32"
echo "   - Buka Arduino IDE"
echo "   - File: firmware/SmartDoorLock_Simple/SmartDoorLock_Simple.ino"
echo "   - Upload ke ESP32"
echo ""
echo "2. Open Serial Monitor (115200 baud)"
echo "   - Cari output: [SEND] OK / [SEND] FAIL"
echo "   - Perhatikan waktu antara log (harus ~2 detik)"
echo ""
echo "3. Test Motion Detection"
echo "   - Gerakkan tangan di depan ESP32"
echo "   - Buzzer harus bunyi SMOOTH tanpa putus-putus"
echo "   - Serial harus show: >>> MOTION DETECTED!"
echo ""
echo "4. Test dengan Server Offline"
echo "   - Matikan dashboard server"
echo "   - ESP32 harus tetap detect motion smooth"
echo "   - Serial show: [SEND] FAIL code=-1 (switched server...)"
echo "   - Motion detection TIDAK boleh lag/freeze"
echo ""
echo "5. Expected Serial Output:"
echo "   [SEND] OK var=0.045 thr=0.060 motion=NO door=LOCKED"
echo "   [SEND] Primary failed (-1), will try fallback next cycle"
echo "   >>> MOTION DETECTED! var=0.125 thr=0.060"
echo ""
echo "✅ PASS if: Motion detection jalan smooth meski server fail"
echo "❌ FAIL if: Buzzer putus-putus atau motion detection lag"
